services:
  server:
    container_name: wazzali-server-dev
    build:
      context: ./
      target: dev
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./src:/usr/src/app/src
  redis:
    container_name: wazzali-redis-dev
    image: redis:latest
    restart: always
    ports:
      - 6379:6379